# spring boot application.yml file
# use mysql server
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name
    username: your_database_username
    password: your_database_password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect