spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=database1;encrypt=true;trustServerCertificate=true
    username: sa
    password: Pass@word
  datasource-second:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc-url: jdbc:sqlserver://localhost:1433;databaseName=database2;encrypt=true;trustServerCertificate=true
    username: sa
    password: Pass@word

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: sql_server